-- 创建数据库
CREATE DATABASE IF NOT EXISTS oa_system DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS oa_workflow DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS oa_hr DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS oa_file DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS oa_dingtalk DEFAULT CHARACTER SET utf8mb4;
